tags_list:
    [
        "низкое качество стирки или чистки",
        "не заменили ковры вовремя",
        "клиент хочет добавить ковры",
        "клиент хочет меньше ковров",
        "погашение долга",
        "расторжение договора",
        "возобновление услуг",
        "долго нет ответа на заявку",
        "произошла лишняя доставка",
        "доставили не те ковры",
        "не выставлен вовремя счет",
        "неверная сумма в счете",
        "ковер забрали без причины",
        "забрали не тот ковер",
        "доставили ковры на неверный адрес",
        "менеджер нагрубил клиенту",
        "клиент недоволен ценами",
        "новый клиент заключение договора",
        "консультация или уточнение деталей",
        "поменять спецификации",
        "клиент уходит к конкурентам",
        "приостановить услуги",
        "ошибка в документах",
        "клиент просит заменять ковры чаще",
        "клиент просит заменять ковры реже",
        "клиент заявляет что ранее подобная проблема уже возникала и это повторный случай",
        "неприемлемое поведение или грубость водителя",
        "плохое качество ковра, неудобный или старый ковер",
        "клиент недоволен и угрожает отказом от услуг"]